### PR TITLE
Destroy method fixes

### PR DESCRIPTION
**Pull request by matthewhall**
Fixes for JS errors thrown when autoplay is enabled.

Thanks.

### CODE REVIEW

**Comment by aofray** [comment]
how to use the method of destroy ???

**Comment by mattstauffer** [comment]
@matthewhall I have no idea why I never got a notification for this PR. Two friggin years. Still care if I merge or not?

**Comment by matthewhall** [comment]
Nope, go ahead man.

**Comment by mattstauffer** [comment]
I should've known.. if I didn't get the notification from the first time around, I wouldnt' get a notification when you responded back.

UGH GITHUB.

Thanks @matthewhall

**Pull request merged**
